// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DebounceController from "./debounce_controller"
application.register("debounce", DebounceController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import RemoveController from "./remove_controller"
application.register("remove", RemoveController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SlideOverController from "./slide_over_controller"
application.register("slide-over", SlideOverController)
