default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: rss_reader_development
  queue:
    <<: *primary_development
    database: rss_reader_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: rss_reader_development_cable
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary_development
    database: rss_reader_development_cache
    migrations_paths: db/cache_migrate

test:
  <<: *default
  database: rss_reader_test

production:
  primary: &primary_production
    <<: *default
    database: rss_reader_production
    username: rss_reader
    password: <%= ENV["RSS_READER_DATABASE_PASSWORD"] %>
    url: <%= ENV['DATABASE_URL'] %>
  queue:
    <<: *primary_production
    database: rss_reader_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rss_reader_production_cable
    migrations_paths: db/cable_migrate
